services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # default in the JetBrains IDE
      - .:/opt/project
      # skip vendor, if you have changed smth, please rebuild
      - /opt/project/vendor
    restart: always
