services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # default in the JetBrains IDE
      - .:/opt/project
    restart: always
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_PASSWORD: '!ChangeMe!'
      POSTGRES_USER: 'app'
    volumes:
      - ./storage/database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
